# Task 1:
1.Write a function to compute 5/0 and use try/except to catch the exceptions.

In [19]:
def zero():
    try:
        5/0
    except ZeroDivisionError:
        print("You are trying to divide by zero")
zero()

You are trying to divide by zero


# 2.
Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].Hint: Subject,Verb and Object should be declared in the program as shown below.subjects=["Americans ","Indians"]verbs=["play","watch"]objects=["Baseball","Cricket"]

In [37]:
subj = ["Americans","Indians"] 
verb = ["Play", "watch"] 
obje = ["Baseball","cricket"]

li = [(sub+" "+ ver + " " +obj+".") for sub in subj for ver in verb for obj in obje]
for x in li:
    print(x)

Americans Play Baseball.
Americans Play cricket.
Americans watch Baseball.
Americans watch cricket.
Indians Play Baseball.
Indians Play cricket.
Indians watch Baseball.
Indians watch cricket.


In [54]:
import numpy as np

def mat(ip,n,incre=False):#the increasing is False
    if not incre:
        opmat=np.array([x**(n-1-i)for x in ip for i in range(n)]).reshape(len(ip),n)#
    return opmat

ipu=([1,2,3,4,5])
col=4
opt=mat(ipu,col,False)

print("\n\n",opt)






 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
